def test():
    raise Exception("fatal error")
